import { test, expect } from '@playwright/test';

async function csrfHeaders(request) {
  await request.get('/healthz');
  const cookies = await request.storageState();
  const csrf = cookies.cookies.find((c) => c.name === 'bi_csrf')?.value;
  return csrf ? { 'x-csrf-token': csrf } : {};
}

const INV_CLIENT = 'Invoice E2E Client';
const INV_PROJECT = 'Invoice E2E Project';
const RATE = 12500;     // $125/hr
const HOURS = 4;

function todayIso() {
  return new Date().toISOString().slice(0, 10);
}

function plusDays(iso, n) {
  const d = new Date(iso);
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

test.describe.serial('invoices', () => {
  let projectId;
  let subId;
  let memberId;
  let invoiceId;
  let publicToken;

  test.describe('super-admin setup + sub logs hours', () => {
    test.use({ storageState: '.auth/super_admin.json' });

    test('creates client/project, adds sub at $125/hr, sub will log later', async ({ request }) => {
      const headers = await csrfHeaders(request);

      const subs = await (await request.get('/api/users?role=subcontractor')).json();
      const sub = subs.users.find((u) => u.email === 'sub@example.com');
      expect(sub).toBeTruthy();
      subId = sub.id;

      const cRes = await request.post('/api/clients', {
        headers,
        data: { name: INV_CLIENT, payment_terms_days: 14 },
      });
      expect(cRes.status()).toBe(201);
      const { client } = await cRes.json();

      const pRes = await request.post('/api/projects', {
        headers,
        data: { client_id: client.id, name: INV_PROJECT },
      });
      expect(pRes.status()).toBe(201);
      const { project } = await pRes.json();
      projectId = project.id;

      const mRes = await request.post(`/api/projects/${project.id}/members`, {
        headers,
        data: { user_id: subId, bill_rate_cents: RATE },
      });
      expect(mRes.status()).toBe(201);
      const { member } = await mRes.json();
      memberId = member.id;
    });
  });

  test.describe('sub logs hours', () => {
    test.use({ storageState: '.auth/subcontractor.json' });

    test('sub posts a time entry on the project', async ({ request }) => {
      const headers = await csrfHeaders(request);
      const tRes = await request.post('/api/time-entries', {
        headers,
        data: {
          project_id: projectId,
          entry_date: todayIso(),
          hours: HOURS,
          description: 'E2E invoice test work',
        },
      });
      expect(tRes.status()).toBe(201);
    });
  });

  test.describe('super-admin: preview, draft, public link', () => {
    test.use({ storageState: '.auth/super_admin.json' });

    test('previews and creates a draft; line rate is snapshotted', async ({ request }) => {
      const headers = await csrfHeaders(request);

      // Preview shows the unbilled time entry at the current rate.
      const previewRes = await request.post('/api/invoices/preview', {
        headers,
        data: { project_id: projectId, through_date: todayIso() },
      });
      expect(previewRes.status()).toBe(200);
      const preview = await previewRes.json();
      expect(preview.lines.length).toBeGreaterThan(0);
      expect(preview.lines[0].kind).toBe('time');
      expect(preview.lines[0].unit_rate_cents).toBe(RATE);
      expect(preview.subtotal_cents).toBe(RATE * HOURS);

      // Create draft.
      const issue = todayIso();
      const due = plusDays(issue, 14);
      const cRes = await request.post('/api/invoices', {
        headers,
        data: {
          project_id: projectId,
          through_date: issue,
          issue_date: issue,
          due_date: due,
          notes: 'Auto-generated by e2e suite.',
        },
      });
      expect(cRes.status()).toBe(201);
      const { invoice } = await cRes.json();
      invoiceId = invoice.id;
      publicToken = invoice.public_token;

      expect(invoice.status).toBe('draft');
      expect(invoice.subtotal_cents).toBe(RATE * HOURS);
      expect(invoice.public_token).toMatch(/^[A-Za-z0-9_-]{32}$/);

      // Snapshot test: change the rate, the existing line stays at $125/hr.
      const rateRes = await request.patch(
        `/api/projects/${projectId}/members/${memberId}`,
        { headers, data: { bill_rate_cents: 99900 } }
      );
      expect(rateRes.status()).toBe(200);

      const detail = await (await request.get(`/api/invoices/${invoiceId}`)).json();
      expect(detail.lines[0].unit_rate_cents).toBe(RATE);
    });

    test('renders the in-app preview pane and the invoices list view', async ({ page }) => {
      await page.goto('/#/invoices');
      await expect(page.locator('h1', { hasText: 'Invoices' })).toBeVisible();
      await expect(page.locator('main')).toContainText(INV_CLIENT);

      await page.goto(`/#/invoices/${invoiceId}`);
      await expect(page.locator('h1')).toContainText(/Invoice 20\d\d-\d{4}/);
      await expect(page.locator('iframe')).toBeVisible();
    });

    test('locked time entry rejects a sub edit with 409', async ({ request, browser }) => {
      // Switch to sub auth via a fresh context.
      const ctx = await browser.newContext({ storageState: '.auth/subcontractor.json' });
      const r = ctx.request;
      const headers = await csrfHeaders(r);
      const list = await (await r.get(`/api/time-entries?project_id=${projectId}&include_locked=1`)).json();
      const locked = list.entries.find((e) => e.locked);
      expect(locked).toBeTruthy();
      const editRes = await r.patch(`/api/time-entries/${locked.id}`, {
        headers,
        data: { hours: 99 },
      });
      expect(editRes.status()).toBe(409);
      await ctx.close();
    });
  });

  test.describe('public unauthenticated invoice view + token lifecycle', () => {
    test.use({ storageState: '.auth/super_admin.json' });   // for rotate/revoke API calls

    test('loads /i/<token> from a fresh browser context and renders invoice HTML', async ({ browser }) => {
      // Explicitly pass empty storageState so the project-level
      // .auth/super_admin.json is NOT inherited (playwright does inherit it
      // into browser.newContext() when test.use({ storageState }) is in
      // scope — the empty override gives us a true unauthenticated visitor).
      // The "no bi_session cookie set on /i/<token>" property is already
      // covered by test/publicInvoice.test.js with supertest.
      const ctx = await browser.newContext({ storageState: { cookies: [], origins: [] } });
      const page = await ctx.newPage();
      const res = await page.goto(`/i/${publicToken}`);
      expect(res?.status()).toBe(200);
      const headers = res.headers();
      expect(headers['cache-control']).toBe('private, no-store');
      expect(headers['x-robots-tag']).toBe('noindex');
      await expect(page.locator('h1')).toContainText('Invoice');
      await expect(page.locator('body')).toContainText(INV_CLIENT);
      await ctx.close();
    });

    test('rotate-token invalidates the old link', async ({ request, browser }) => {
      const headers = await csrfHeaders(request);
      const oldToken = publicToken;
      const rotated = await request.post(`/api/invoices/${invoiceId}/rotate-token`, { headers });
      expect(rotated.status()).toBe(200);
      const { invoice: rotInv } = await rotated.json();
      expect(rotInv.public_token).not.toBe(oldToken);
      publicToken = rotInv.public_token;

      const ctx = await browser.newContext({ storageState: { cookies: [], origins: [] } });
      const stale = await ctx.request.get(`/i/${oldToken}`);
      expect(stale.status()).toBe(404);
      const fresh = await ctx.request.get(`/i/${publicToken}`);
      expect(fresh.status()).toBe(200);
      await ctx.close();
    });

    test('revoke-token returns 410 to public visitors', async ({ request, browser }) => {
      const headers = await csrfHeaders(request);
      const r = await request.post(`/api/invoices/${invoiceId}/revoke-token`, { headers });
      expect(r.status()).toBe(200);

      const ctx = await browser.newContext({ storageState: { cookies: [], origins: [] } });
      const after = await ctx.request.get(`/i/${publicToken}`);
      expect(after.status()).toBe(410);
      await ctx.close();
    });
  });

  test.describe('cleanup: void detaches sources', () => {
    test.use({ storageState: '.auth/super_admin.json' });

    test('void unlocks the previously-locked time entry', async ({ request }) => {
      const headers = await csrfHeaders(request);
      const v = await request.post(`/api/invoices/${invoiceId}/void`, { headers });
      expect(v.status()).toBe(200);

      const list = await (await request.get(`/api/time-entries?project_id=${projectId}&include_locked=1`)).json();
      expect(list.entries.every((e) => !e.locked)).toBe(true);
    });
  });
});
